using System.Collections;
using FallenForest.Audio;using FallenForest.Core;using FallenForest.Player;using FallenForest.UI;using UnityEngine;using UnityEngine.UI;
namespace FallenForest.Cinematics
{
    public sealed class EndSequence:MonoBehaviour
    {
        [SerializeField]private Terrain terrain;[SerializeField]private GameObject car;[SerializeField]private AudioSource carAudio;[SerializeField]private AudioDirector audioDirector;[SerializeField]private CanvasGroup fade;[SerializeField]private Text endText;[SerializeField]private Material roadMaterial;[SerializeField]private float escapeRunTime=2.35f,carPassTime=1.65f,sitTime=1.8f;private bool started;private GameObject runtimeRoad;
        public void Begin(PlayerMotor player,Vector3 boundaryPoint,Vector3 outwardDirection){if(started||player==null)return;StartCoroutine(Run(player,boundaryPoint,outwardDirection));}
        public void Begin(PlayerMotor player){Vector3 o=player!=null?Vector3.ProjectOnPlane(player.transform.forward,Vector3.up).normalized:Vector3.forward;Begin(player,player!=null?player.transform.position:transform.position,o);}
        private IEnumerator Run(PlayerMotor player,Vector3 boundaryPoint,Vector3 outward)
        {
            started=true;outward=Vector3.ProjectOnPlane(outward,Vector3.up).normalized;if(outward.sqrMagnitude<.001f)outward=Vector3.forward;Vector3 tangent=Vector3.Cross(Vector3.up,outward).normalized;CameraMotion cam=FindFirstObjectByType<CameraMotion>();player.SetControlsEnabled(false);cam?.SetInputEnabled(false);cam?.AddShake(.055f,3.2f);HUDController.Instance?.ShowMessage("БЕГИ");Vector3 edge=Ground(boundaryPoint+outward*1.2f),forestExit=Ground(edge+outward*8.5f),roadside=Ground(edge+outward*16f),sitting=Ground(edge+outward*18.3f-tangent*.7f);BuildRoad(roadside,tangent);Transform actor=player.transform;yield return MoveActor(actor,forestExit,escapeRunTime,outward);yield return MoveActor(actor,roadside,.55f,outward);
            if(car!=null){Vector3 start=Ground(roadside-tangent*31f)+Vector3.up*.72f,end=Ground(roadside+tangent*31f)+Vector3.up*.72f;car.SetActive(true);car.transform.SetPositionAndRotation(start,Quaternion.LookRotation(tangent));carAudio?.Play();float t=0;while(t<carPassTime){t+=Time.deltaTime;car.transform.position=Vector3.Lerp(start,end,Mathf.SmoothStep(0,1,Mathf.Clamp01(t/carPassTime)));yield return null;}carAudio?.Stop();car.SetActive(false);}
            audioDirector?.HardSilence();yield return new WaitForSecondsRealtime(1.05f);yield return RotateActor(actor,Quaternion.LookRotation(-outward),1.15f);yield return new WaitForSecondsRealtime(.65f);yield return MoveActor(actor,sitting,sitTime,-outward);if(fade!=null){fade.blocksRaycasts=true;float t=0;while(t<2.45f){t+=Time.unscaledDeltaTime;fade.alpha=Mathf.Clamp01(t/2.45f);yield return null;}}if(endText!=null){endText.text="КОНЕЦ";endText.gameObject.SetActive(true);}yield return new WaitForSecondsRealtime(4f);SceneFlow.MainMenu();
        }
        private Vector3 Ground(Vector3 p){Terrain t=terrain!=null?terrain:Terrain.activeTerrain;if(t==null)return p;p.y=t.SampleHeight(p)+t.transform.position.y+.03f;return p;}
        private void BuildRoad(Vector3 centre,Vector3 tangent){if(runtimeRoad!=null)Destroy(runtimeRoad);runtimeRoad=GameObject.CreatePrimitive(PrimitiveType.Cube);runtimeRoad.name="FinalRoad_Runtime";runtimeRoad.transform.position=centre-Vector3.up*.09f;runtimeRoad.transform.rotation=Quaternion.LookRotation(tangent);runtimeRoad.transform.localScale=new Vector3(8.8f,.16f,72f);Collider c=runtimeRoad.GetComponent<Collider>();if(c!=null)c.enabled=false;Renderer r=runtimeRoad.GetComponent<Renderer>();if(r!=null&&roadMaterial!=null)r.sharedMaterial=roadMaterial;}
        private IEnumerator MoveActor(Transform actor,Vector3 target,float duration,Vector3 face){Vector3 start=actor.position;Quaternion sr=actor.rotation,er=face.sqrMagnitude>.001f?Quaternion.LookRotation(face):sr;float t=0;while(t<duration){t+=Time.deltaTime;float u=Mathf.SmoothStep(0,1,Mathf.Clamp01(t/Mathf.Max(.01f,duration)));actor.position=Vector3.Lerp(start,target,u);actor.rotation=Quaternion.Slerp(sr,er,u);yield return null;}}
        private IEnumerator RotateActor(Transform actor,Quaternion target,float duration){Quaternion start=actor.rotation;float t=0;while(t<duration){t+=Time.unscaledDeltaTime;actor.rotation=Quaternion.Slerp(start,target,Mathf.SmoothStep(0,1,Mathf.Clamp01(t/duration)));yield return null;}}
    }
}
