using System.Collections;
using FallenForest.Monsters;
using FallenForest.Player;
using FallenForest.UI;
using UnityEngine;
namespace FallenForest.Cinematics
{
    public sealed class JumpscareController : MonoBehaviour
    {
        [SerializeField]private AudioSource source;[SerializeField]private AudioClip[] locustScreamers;[SerializeField]private CanvasGroup blackout;[SerializeField]private PlayerMotor playerMotor;[SerializeField]private CameraMotion cameraMotion;[SerializeField]private Transform jumpscareAnchor;[SerializeField]private float blackHold=1.3f;[SerializeField]private DeathMenuController deathMenu;private bool busy;
        public void KillByLocust(LocustAI locust,Transform player){if(!busy)StartCoroutine(KillRoutine(locust));}
        private IEnumerator KillRoutine(LocustAI locust){busy=true;if(playerMotor==null)playerMotor=FindFirstObjectByType<PlayerMotor>();if(cameraMotion==null)cameraMotion=FindFirstObjectByType<CameraMotion>();playerMotor?.SetControlsEnabled(false);cameraMotion?.SetInputEnabled(false);int variant=Random.Range(0,2);locust?.PrepareJumpscareVariant(variant);if(source!=null&&locustScreamers!=null&&locustScreamers.Length>0){source.clip=locustScreamers[Mathf.Clamp(variant,0,locustScreamers.Length-1)];source.pitch=1;source.Play();}if(variant==0)yield return JumpscareA(locust);else yield return JumpscareB(locust);if(blackout!=null)blackout.alpha=1;yield return new WaitForSecondsRealtime(blackHold);source?.Stop();if(locust!=null)Destroy(locust.gameObject);cameraMotion?.ClearCinematicFov();if(deathMenu==null)deathMenu=FindFirstObjectByType<DeathMenuController>();deathMenu?.Show();busy=false;}
        private IEnumerator JumpscareA(LocustAI locust){cameraMotion?.SetCinematicFov(52);cameraMotion?.AddShake(.24f,.50f);if(locust==null||jumpscareAnchor==null){yield return new WaitForSecondsRealtime(.82f);yield break;}Vector3 start=locust.transform.position;Quaternion sr=locust.transform.rotation;float duration=.82f,t=0;while(t<duration){t+=Time.unscaledDeltaTime;float p=Mathf.Clamp01(t/duration),e=1f-Mathf.Pow(1f-p,3f);locust.transform.position=Vector3.Lerp(start,jumpscareAnchor.position,e);Quaternion target=jumpscareAnchor.rotation*Quaternion.Euler(Mathf.Sin(p*21f)*5f,0,Mathf.Sin(p*32f)*4f);locust.transform.rotation=Quaternion.Slerp(sr,target,e);if(p>.58f)cameraMotion?.AddShake(.18f+p*.11f,.9f);yield return null;}}
        private IEnumerator JumpscareB(LocustAI locust){cameraMotion?.SetCinematicFov(68);cameraMotion?.AddShake(.12f,.36f);if(locust==null||jumpscareAnchor==null){yield return new WaitForSecondsRealtime(1.02f);yield break;}Vector3 start=locust.transform.position,side=jumpscareAnchor.right*(Random.value<.5f?-1.25f:1.25f),control=jumpscareAnchor.position+side+jumpscareAnchor.forward*.8f+Vector3.up*.35f,end=jumpscareAnchor.position+jumpscareAnchor.forward*.02f;float duration=1.02f,t=0;while(t<duration){t+=Time.unscaledDeltaTime;float p=Mathf.Clamp01(t/duration),one=1f-p;locust.transform.position=one*one*start+2*one*p*control+p*p*end;Quaternion target=jumpscareAnchor.rotation*Quaternion.Euler(-7f+p*15f,Mathf.Sin(p*18f)*10f,(p-.5f)*24f);locust.transform.rotation=Quaternion.Slerp(locust.transform.rotation,target,1f-Mathf.Exp(-15f*Time.unscaledDeltaTime));if(p>.45f)cameraMotion?.AddShake(.11f+p*.16f,.68f);yield return null;}cameraMotion?.SetCinematicFov(47);yield return new WaitForSecondsRealtime(.09f);}
    }
}
